let modeloJson = [
  {
    id: 1,
    name: 'Camiseta Azul Marinho',
    img: 'img/camisetaA.jpg',
    price: 29.99,
    sizes: ['malha', 'algodão', 'dry'],
    description: 'Blusa Básica Manga Curta',
  },
  {
    id: 2,
    name: 'Camiseta Amarela',
    img: 'img/camisetaAM.jpg',
    price: 29.99,
    sizes: ['algodão', 'malha', 'dry'],
    description: 'Blusa Básica Manga Curta',
  },
  {
    id: 3,
    name: 'Camiseta Marrom',
    img: 'img/camisetaM.jpg',
    price: 39.99,
    sizes: ['dry', 'malha', 'algodão'],
    description: 'Blusa Básica Manga Curta',
  },
  {
    id: 4,
    name: 'Camiseta Preta',
    img: 'img/CamisetaP.jpg',
    price: 39.99,
    sizes: ['algodão', 'malha', 'dry'],
    description: 'Blusa Básica Manga Curta',
  },
  {
    id: 5,
    name: 'Camiseta Rosa Choque',
    img: 'img/CamisetaPK.jpg',
    price: 49.99,
    sizes: ['malha', 'algodão', 'dry'],
    description: 'Blusa Básica Manga Curta',
  },
  {
    id: 6,
    name: 'Camiseta Rosa Claro',
    img: 'img/CamisetaR.jpg',
    price: 49.99,
    sizes: ['malha', 'dry', 'algodão'],
    description: 'Blusa Básica Manga Curta',
  },
  {
    id: 7,
    name: 'Camiseta Vermelha',
    img: 'img/CamisetaV.jpg',
    price: 59.99,
    sizes: ['malha', 'dry', 'dry'],
    description: 'Blusa Básica Manga Curta',
  },
  {
    id: 8,
    name: 'Camiseta Cruzeiro Limitada',
    img: 'img/CamisetaCruzeiro.jpg',
    price: 299.99,
    sizes: ['malha', 'dry', 'dry'],
    description: 'Blusa Básica Manga Curta',
  },
  {
    id: 9,
    name: 'Camiseta Brasil Limitada',
    img: 'img/CamisaBrasil.jpg',
    price: 399.99,
    sizes: ['malha', 'dry', 'dry'],
    description: 'Blusa Básica Manga Curta',
  }
]